"""Initial migration

Revision ID: 822d6c173845
Revises: 
Create Date: 2026-02-24 18:58:51.083588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822d6c173845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=2048), nullable=True),
    sa.Column('short', sa.String(length=6), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_map_short'), ['short'], unique=True)
        batch_op.create_index(batch_op.f('ix_url_map_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_map_timestamp'))
        batch_op.drop_index(batch_op.f('ix_url_map_short'))

    op.drop_table('url_map')
    # ### end Alembic commands ###
